// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcZaNvJShR6G0UNkrmN3s2PZ9duK8nvC0',
    appId: '1:434118252750:web:30e04b0bb5e7051ea2989f',
    messagingSenderId: '434118252750',
    projectId: 'chattiemporeal-e454e',
    authDomain: 'chattiemporeal-e454e.firebaseapp.com',
    storageBucket: 'chattiemporeal-e454e.firebasestorage.app',
    measurementId: 'G-XCPNXSN0J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKVqU7flZXJdYoSyAROm8ncwoPgx7VK9s',
    appId: '1:434118252750:android:8fdcf901b412004ea2989f',
    messagingSenderId: '434118252750',
    projectId: 'chattiemporeal-e454e',
    storageBucket: 'chattiemporeal-e454e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArnwtkBLDrINPZ-qj_QbvKO07uu4xtLUc',
    appId: '1:434118252750:ios:04852a230e971b5da2989f',
    messagingSenderId: '434118252750',
    projectId: 'chattiemporeal-e454e',
    storageBucket: 'chattiemporeal-e454e.firebasestorage.app',
    iosBundleId: 'com.example.appconductor2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArnwtkBLDrINPZ-qj_QbvKO07uu4xtLUc',
    appId: '1:434118252750:ios:04852a230e971b5da2989f',
    messagingSenderId: '434118252750',
    projectId: 'chattiemporeal-e454e',
    storageBucket: 'chattiemporeal-e454e.firebasestorage.app',
    iosBundleId: 'com.example.appconductor2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcZaNvJShR6G0UNkrmN3s2PZ9duK8nvC0',
    appId: '1:434118252750:web:4e2ffda92dd4142ba2989f',
    messagingSenderId: '434118252750',
    projectId: 'chattiemporeal-e454e',
    authDomain: 'chattiemporeal-e454e.firebaseapp.com',
    storageBucket: 'chattiemporeal-e454e.firebasestorage.app',
    measurementId: 'G-2SZ2YKV3PB',
  );
}
